apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  sso: |
    issuer: http://dex:5556/dex
    issuerAlias: http://dex:5556/dex
    # ca.pem associated with the self-signed cert in manifests/components/sso/dex/dex-cm.yaml
    # Expires on 2035/11/07
    rootCA: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIUQtEgS/Z6ef3cyNilxRqdN9ulKgIwDQYJKoZIhvcNAQEL
      BQAwEjEQMA4GA1UEAwwHa3ViZS1jYTAeFw0yNTExMDkwMjMwMTRaFw0zNTExMDcw
      MjMwMTRaMBIxEDAOBgNVBAMMB2t1YmUtY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
      DwAwggEKAoIBAQCbqjMoVVBlXW5WmWFKwLsWmVPGHPr08xhYhxv93vIJn2THUFV5
      JYsGxcxbejCdfLuMR0S2PolOcB+hxczrObQrxqV+uB8ZDPNsui5NnO31pDZRpDVr
      9j8yPztXTvG+68lmZ/tae7va5irhfBWI8dTCYCDkDwCzlfeywJpzVYOo5oMRHuTa
      VrxNwkQ5gkW0hoE17lgVo/v/YI/Vd2UOhl6pM2/SB9UtqNNfFQMc3V2VcH1fMuDl
      IoLGDLIvuVFdQSVjdkiuy0KFIsvnwQTkcGjMQF5v8ls4jkAW9M5vElJHx9Mbwj8H
      I/DfXp2vMYvkZtld9dOBbsjsvqWPMA88MI7bAgMBAAGjUzBRMB0GA1UdDgQWBBTM
      hwtyqDYIUolMTIjyFmK0b6M3wDAfBgNVHSMEGDAWgBTMhwtyqDYIUolMTIjyFmK0
      b6M3wDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCQqihzKk6I
      XgW1RExaBu4CBQ9B704Ic/CkIl18NSWgo1nfxrkMCoFIh12dUpTlUTUBV+qYh+dU
      5CVQ2Lyo/ep8uAGYtC383O1unskzxW9unzOQkYewkzbYL7j9ixPRASy3cJDpxcpR
      4/PtHXkV/CHk7Jh0SKAj7oh8gUeAg7GX6uXZpViFOOdqWjQ8PfFZyRUKXmLu54s+
      i2yVF8Co5hPsgvXMi4F9nx5FztPYMwtlAI8Mjn+i7mc8CaHBR6T6gxR6uYv/olz6
      5aWBxRx29MfX2fLjZgX4gDows9ipaZ77QbExhVZUjCQRLiYr4C0pxCQU14g6ZAzz
      neiNk3Rz9eFt
      -----END CERTIFICATE-----
    clientId:
      name: argo-server-sso
      key: clientID
    clientSecret:
      name: argo-server-sso
      key: clientSecret
    redirectUrl: http://localhost:8080/oauth2/callback
    scopes:
    - groups
    - email
    - profile
    rbac:
      enabled: true
