blank_issues_enabled: false

contact_links:
  - name: Have you read the docs?
    url: https://argoproj.github.io/argo-workflows/
    about: Much help can be found in the docs
  - name: Ask a question
    url: https://github.com/argoproj/argo-workflows/discussions/new
    about: Ask a question or start a discussion about workflows
  - name: Chat on Slack
    url: https://argoproj.github.io/community/join-slack
    about: Maybe chatting with the community can help
