apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - argo-pgcat-config-secret.yaml
  - pgcat-deployment.yaml
  - pgcat-service.yaml

patches:
  - path: overlays/workflow-controller-configmap.yaml