apiVersion: v1
kind: Service
metadata:
  name: postgres-tertiary
  namespace: argo
  labels:
    app: postgres-failover-test
    service-type: tertiary
spec:
  selector:
    app: postgres-failover-test
    postgres-tertiary: "true"
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP