apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ./argo-server-rbac
  - ./workflow-controller-rbac

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: workflow-controller
    path: ./overlays/workflow-controller-deployment.yaml
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: argo-server
    path: ./overlays/argo-server-deployment.yaml
