apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-from-configmap-
  annotations:
    workflows.argoproj.io/description: |
      This example demonstrates loading parameter values from a ConfigMap.
      Note that the "simple-parameters" ConfigMap (defined in `examples/configmaps/simple-parameters-configmap.yaml`) needs to be created first before submitting this workflow.
    workflows.argoproj.io/verify.py: |
      assert status["phase"] == "Succeeded"
spec:
  entrypoint: print-message-from-configmap

  templates:
  - name: print-message-from-configmap
    inputs:
      parameters:
      # Parameters can also be passed via configmap reference.
      - name: message
        valueFrom:
          configMapKeyRef:
            name: simple-parameters
            key: msg
    container:
      image: busybox
      command: ["echo"]
      args: ["{{inputs.parameters.message}}"]
