apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: global-parameter-values-from-configmap-referenced-as-local-variable-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      This example demonstrates global parameter values from configmap can be referenced as template local variable.
      Note that the "simple-parameters" ConfigMap (defined in examples/configmaps/simple-parameters-configmap.yaml)
      needs to be created first before submitting this workflow.
    workflows.argoproj.io/verify.py: |
      assert status["phase"] == "Succeeded"
spec:
  serviceAccountName: argo
  entrypoint: whalesay
  arguments:
    parameters:
      - name: message
        valueFrom:
          configMapKeyRef:
            name: simple-parameters
            key: msg
  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
