apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: global-parameter-values-from-configmap-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      This example demonstrates loading global parameter values from a ConfigMap.
      Note that the "simple-parameters" ConfigMap (defined in `examples/configmaps/simple-parameters-configmap.yaml`) needs to be created first before submitting this workflow.
spec:
  entrypoint: whalesay
  # Parameters can also be passed via configmap reference.
  arguments:
    parameters:
    - name: message
      valueFrom:
        configMapKeyRef:
          name: simple-parameters
          key: msg

  templates:
  - name: print-message
    container:
      image: busybox
      command: ["echo"]
      args: ["{{workflow.parameters.message}}"]
