apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespace-install
  - minio
  - workflow-role.yaml
  - workflow-default-rolebinding.yaml
  - cluster-workflow-template-rbac.yaml
  - artifact-repositories-configmap.yaml

patchesStrategicMerge:
  - overlays/workflow-controller-configmap.yaml
