apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespace-install
  - minio
  - webhooks
  - argo-server-sso-secret.yaml
  - workflow-role.yaml
  - kubelet-executor-clusterrole.yaml
  - kubelet-executor-default-clusterrolebinding.yaml
  - workflow-default-rolebinding.yaml
  - cluster-workflow-template-rbac.yaml
  - artifact-repositories-configmap.yaml
  - hello-controller-plugin-configmap.yaml

patchesStrategicMerge:
  - overlays/workflow-controller-configmap.yaml
  - overlays/argo-server-deployment.yaml
  - overlays/workflow-controller-deployment.yaml
