apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../namespace-install
  - ../../namespace-install/argo-server-read-only
  - minio

resources:
  - argo-server-sso-secret.yaml
  - workflow-role.yaml
  - workflow-default-rolebinding.yaml
  - cluster-workflow-template-rbac.yaml

patchesStrategicMerge:
  - overlays/argo-server-deployment.yaml
  - overlays/argo-server-read-only-sa.yaml
  - overlays/argo-server-sa.yaml
  - overlays/workflow-controller-configmap.yaml
