apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../namespace-install
  - minio

resources:
  - workflow-role.yaml
  - workflow-default-rolebinding.yaml
  - cluster-workflow-template-rbac.yaml

patchesStrategicMerge:
  - overlays/workflow-controller-configmap.yaml