apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../cluster-install
  - minio
  - httpbin
  - webhooks
  - default.service-account-token-secret.yaml
  - argo-server-sso-secret.yaml
  - executor/emissary/executor-role.yaml
  - executor-default-rolebinding.yaml
  - pod-manager-role.yaml
  - pod-manager-default-rolebinding.yaml
  - workflow-manager-role.yaml
  - workflow-manager-default-rolebinding.yaml
  - agent-role.yaml
  - agent-default-rolebinding.yaml
  - artifactgc-role.yaml
  - artifactgc-default-rolebinding.yaml
  - cluster-workflow-template-rbac.yaml
  - artifact-repositories-configmap.yaml

patches:
  - path: overlays/workflow-controller-configmap.yaml
  - path: overlays/argo-server-deployment.yaml
