# https://argoproj.github.io/argo-workflows/workflow-rbac/
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role
rules:
  # pod get/watch is used to identify the container IDs of the current pod
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      # pod patch is used to annotate the step's outputs back to controller (e.g. artifact location)
      # This is ONLY needed if the step/task has outputs that are used by another step or task.
      - patch
  # thing patch is used to share the step's outputs back to controller
  - apiGroups:
      - argoproj.io
    resources:
      - workflowthings
    verbs:
      - patch
  # logs get/watch are used to get the pods logs for script outputs, and for log archival
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - watch
      # This allows one workflow to create another.
      # E.g. for resource templates.
      - create
      - patch
      - get
