apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.argoproj.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: Status of the workflow
    name: Status
    type: string
  - JSONPath: .status.startedAt
    description: When the workflow was started
    name: Started
    format: date-time
    type: date
  - JSONPath: .status.finishedAt
    description: When the workflow was finished
    name: Finished
    format: date-time
    type: date
  group: argoproj.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Workflow
    plural: workflows
    shortNames:
    - wf
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflowtemplates.argoproj.io
spec:
  group: argoproj.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: WorkflowTemplate
    plural: workflowtemplates
    shortNames:
    - wftmpl
