apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argoproj.io_clusterworkflowtemplates.yaml
- argoproj.io_cronworkflows.yaml
- argoproj.io_workflows.yaml
- argoproj.io_workflowtemplates.yaml
- argoproj.io_workfloweventbindings.yaml
