kind: Secret
apiVersion: v1
metadata:
  name: argo-workflows-webhook-clients
# The data keys must be the name of a service account.
stringData:
  # https://support.atlassian.com/bitbucket-cloud/docs/manage-webhooks/
  bitbucket.org: |
    type: bitbucket
    secret: "my-uuid"
  # https://confluence.atlassian.com/bitbucketserver/managing-webhooks-in-bitbucket-server-938025878.html
  bitbucketserver: |
    type: bitbucketserver
    secret: "shh!"
  # https://developer.github.com/webhooks/securing/
  github.com: |
    type: github
    secret: "shh!"
  # https://docs.gitlab.com/ee/user/project/integrations/webhooks.html
  gitlab.com: |
    type: gitlab
    secret: "shh!"
  # https://developers.facebook.com/docs/graph-api/webhooks/getting-started/#event-notifications
  facebook.com: |
    type: x-hub
    secret: "shh!shh!"
  # https://shopify.dev/docs/apps/build/webhooks/subscribe/https#step-2-validate-the-origin-of-your-webhook-to-ensure-its-coming-from-shopify
  shopify.com: |
    type: x-hub
    secret: "shh!shh!"
    x-hub-header-name: X-Shopify-Hmac-SHA256
    x-hub-encoding: base64
  forgejo: |
    type: x-hub
    secret: "shh!shh!"
