apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - haproxy-config.yaml
  - haproxy-deployment.yaml
  - haproxy-service.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-rbac.yaml