apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - haproxy-config.yaml
  - haproxy-deployment.yaml
  - haproxy-service.yaml
  - postgres-deployment.yaml
  - postgres-primary-service.yaml
  - postgres-secondary-service.yaml
  - postgres-tertiary-service.yaml