apiVersion: v1
kind: Service
metadata:
  name: postgres-secondary
  namespace: argo
  labels:
    app: postgres-failover-test
    service-type: secondary
spec:
  selector:
    app: postgres-failover-test
    postgres-secondary: "true"
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP