apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: argo
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: postgres-pod
      containers:
        - name: postgres
          image: isubasinghe/spilo-17:4.0-p3
          env:
            - name: SCOPE
              value: "postgres-cluster"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PATRONI_SUPERUSER_USERNAME
              value: "postgres"
            - name: PATRONI_SUPERUSER_PASSWORD
              value: "password"
            - name: PATRONI_REPLICATION_USERNAME
              value: "standby"
            - name: PATRONI_REPLICATION_PASSWORD
              value: "password"
            - name: PATRONI_KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PATRONI_KUBERNETES_LABELS
              value: '{"app": "postgres"}'
            - name: PATRONI_KUBERNETES_SCOPE_LABEL
              value: "postgres-cluster"
            - name: PATRONI_KUBERNETES_USE_ENDPOINTS
              value: "true"
          ports:
            - containerPort: 5432
            - containerPort: 8008
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8008
            initialDelaySeconds: 3
            periodSeconds: 3