apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-pod
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-pod
  namespace: argo
rules:
- apiGroups: [""]
  resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
  verbs: ["create", "get", "list", "patch", "update", "watch", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-pod
  namespace: argo
subjects:
- kind: ServiceAccount
  name: postgres-pod
  namespace: argo
roleRef:
  kind: Role
  name: postgres-pod
  apiGroup: rbac.authorization.k8s.io