apiVersion: v1
data:
  sso : |
    issuer: http://dex:5556/dex
    clientId: argo-server
    clientSecret:
      name: argo-server-sso
      key: clientSecret
    redirectUrl: https://localhost:2746/oauth2/callback
  rbac: |
    rules:
      - groups:
        - authors
        serviceAccount:
          name: argo-server
    defaultServiceAccount:
      name: argo-server-read-only
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: my-bucket
      endpoint: minio:9000
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
  metricsConfig: |
    disableLegacy: true
    enabled: true
    path: /metrics
    port: 9090
  links: |
    - name: Example Workflow Link
      scope: workflow
      url: http://logging-facility?namespace=${metadata.namespace}&workflowName=${metadata.name}
    - name: Example Pod Link
      scope: pod
      url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
