name: Deploy

on:
  push:
    branches:
      - master
      - dev-pages

jobs:
  deploy:
    if: github.repository == 'argoproj/argo-workflows'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16'
      - run: pip install mkdocs==1.0.4 mkdocs_material==4.1.1
      - run: mkdocs build
      - run: make parse-examples
      - uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./site
