name: SDKs
on:
  push:
    tags:
      - v*
      - 'v3.2.*'
      - 'v3.1.*'
    branches:
      - dev-*
      - python-sdk
jobs:
  sdk:
    if: github.repository == 'terrytangyuan/argo-workflows'
    runs-on: ubuntu-latest
    name: Publish SDK
    strategy:
      matrix:
        name:
        # - java
        - python
    steps:
      - uses: actions/checkout@v2
      - run: make --directory sdks/${{matrix.name}} publish -B
        env:
          JAVA_SDK_MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/create-pull-request@v3
        with:
          title: 'chore: updated ${{matrix.name}} SDK'
          commit-message: 'chore: updated ${{matrix.name}} SDK'
          branch: create-pull-request/sdk/${{matrix.name}}
          signoff: true
