name: SDKs
on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  sdks:
    name: Publish SDKs
    if: github.repository == 'argoproj/argo-workflows'
    permissions:
      packages: write # for publishing packages
      contents: write  # for creating releases
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        name:
        - java
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: make --directory sdks/${{matrix.name}} publish -B
        env:
          JAVA_SDK_MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
