name: Snyk
on:
  schedule:
    - cron: "30 2 * * *"
  push:
    branches:
      - main
      - release-*

permissions:
  contents: read

jobs:
  # we do not scan images here, they're scanned here: https://app.snyk.io/org/argoproj/projects

  golang:
    name: Scan Go deps
    if: github.repository == 'argoproj/argo-workflows'
    runs-on: ubuntu-24.04
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - run: mkdir -p ui/dist/app/ && touch ui/dist/app/placeholder
      - name: Run Snyk to check for Go vulnerabilities
        uses: snyk/actions/golang@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
        with:
          args: --severity-threshold=high

  node:
    name: Scan Node deps
    if: github.repository == 'argoproj/argo-workflows'
    runs-on: ubuntu-24.04
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: "20" # change in all GH Workflows
          cache: yarn
          cache-dependency-path: ui/yarn.lock
      - run: yarn --cwd ui install
      - name: Run Snyk to check for Node vulnerabilities
        uses: snyk/actions/node@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
        with:
          args: --file=ui/package.json --severity-threshold=high
